import { rm } from "node:fs/promises";
import { build } from "esbuild";

await rm("dist", { recursive: true, force: true });

await build({
  entryPoints: {
    index: "extensions/index.ts",
    "hunk-feedback": "extensions/hunk-feedback.ts",
  },
  outdir: "dist",
  entryNames: "[name]",
  bundle: true,
  format: "esm",
  platform: "node",
  target: "node22.19",
  minify: true,
  treeShaking: true,
  legalComments: "none",
  sourcemap: false,
  external: ["@earendil-works/*"],
  banner: {
    js: "// Generated by npm run build. Do not edit dist files directly.",
  },
  logLevel: "info",
});
