import { rm } from "node:fs/promises";
import { build } from "esbuild";

await rm("dist", { recursive: true, force: true });

await build({
  entryPoints: { index: "extensions/index.ts" },
  outdir: "dist",
  entryNames: "[name]",
  chunkNames: "chunks/[name]-[hash]",
  bundle: true,
  splitting: true,
  format: "esm",
  platform: "node",
  target: "node22.19",
  minify: true,
  treeShaking: true,
  legalComments: "none",
  sourcemap: false,
  external: ["@earendil-works/*", "@coder/libghostty-vt-node", "zigpty"],
  banner: {
    js: "// Generated by npm run build. Do not edit dist/index.js directly.",
  },
  logLevel: "info",
});
