import { rm } from "node:fs/promises";
import { build } from "esbuild";

await rm("dist", { recursive: true, force: true });

const shared = {
  outdir: "dist",
  bundle: true,
  format: "esm",
  platform: "node",
  target: "node22.19",
  minify: true,
  treeShaking: true,
  legalComments: "none",
  sourcemap: false,
  banner: {
    js: "// Generated by npm run build. Do not edit dist files directly.",
  },
  logLevel: "info",
};

await build({
  ...shared,
  entryPoints: { index: "extensions/index.ts" },
  external: ["@earendil-works/*", "effect"],
});

// Hunk loads this file in its own Bun process, outside the host's package resolver.
// Keep the bridge self-contained at that boundary.
await build({
  ...shared,
  entryPoints: { "hunk-feedback": "extensions/hunk-feedback.ts" },
  external: ["@earendil-works/*"],
});
